/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    categories: Category;
    media: Media;
    products: Product;
    brands: Brand;
    campaigns: Campaign;
    reviews: Review;
    coupons: Coupon;
    pages: Page;
    couponBanners: CouponBanner;
    heroCarousel: HeroCarousel;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    campaigns: CampaignsSelect<false> | CampaignsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    couponBanners: CouponBannersSelect<false> | CouponBannersSelect<true>;
    heroCarousel: HeroCarouselSelect<false> | HeroCarouselSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    faq: Faq;
    homepage: Homepage;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  /**
   * Determines what parts of the dashboard this user can access.
   */
  role: 'admin' | 'manager' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  /**
   * URL identifier (e.g., "mens-clothing").
   */
  slug: string;
  parent?: (string | null) | Category;
  image?: (string | null) | Media;
  /**
   * SEO aur category page par nazar aane wala text.
   */
  description?: string | null;
  /**
   * Wide image for large screens (e.g. 1500x400).
   */
  desktopBanner?: (string | null) | Media;
  /**
   * Tall/Square image for mobile screens.
   */
  mobileBanner?: (string | null) | Media;
  seo?: {
    /**
     * Browser tab aur search results mein nazar aane wala title (50-60 chars).
     */
    metaTitle?: string | null;
    /**
     * Search results ke liye summary (150-160 chars).
     */
    metaDescription?: string | null;
    /**
     * Jab ye page Facebook ya WhatsApp par share hoga, to ye image dikhegi.
     */
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  assetCategory: 'products' | 'categories' | 'banners' | 'general' | 'custom';
  customFolderName?: string | null;
  cloudinaryId?: string | null;
  cloudinaryUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  /**
   * Unique URL part (e.g. usama-ali-shirts)
   */
  slug: string;
  videoUrl?: string | null;
  variants: {
    name: string;
    sku: string;
    price: number;
    salePrice?: number | null;
    stock?: number | null;
    inStock?: boolean | null;
    images?: (string | Media)[] | null;
    attributes?:
      | {
          name?: string | null;
          value?: string | null;
          id?: string | null;
        }[]
      | null;
    weight?: number | null;
    dimensions?: {
      height?: number | null;
      width?: number | null;
      depth?: number | null;
    };
    id?: string | null;
  }[];
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  categories: (string | Category)[];
  brand?: (string | null) | Brand;
  specifications?:
    | {
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  shippingAndReturns?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  rating?: number | null;
  activeCampaigns?: (string | Campaign)[] | null;
  isBestSeller?: boolean | null;
  isNewArrival?: boolean | null;
  isFeatured?: boolean | null;
  isOnDeal?: boolean | null;
  seo?: {
    /**
     * Browser tab aur search results mein nazar aane wala title (50-60 chars).
     */
    metaTitle?: string | null;
    /**
     * Search results ke liye summary (150-160 chars).
     */
    metaDescription?: string | null;
    /**
     * Jab ye page Facebook ya WhatsApp par share hoga, to ye image dikhegi.
     */
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: string;
  name: string;
  /**
   * Unique URL identifier (e.g., "nike" or "best-design").
   */
  slug: string;
  /**
   * Brand ka logo upload karein (e.g., JPEG, PNG, SVG).
   */
  logo?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns".
 */
export interface Campaign {
  id: string;
  title: string;
  slug: string;
  description?: string | null;
  isActive?: boolean | null;
  startDate?: string | null;
  endDate?: string | null;
  banner?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  /**
   * Jis user ne review diya hai.
   */
  user: string | User;
  /**
   * Jis product ke liye review hai.
   */
  product: string | Product;
  rating: number;
  comment: string;
  reviewImage?: (string | null) | Media;
  /**
   * Frontend par show karne ke liye approval zaroori hai.
   */
  isApproved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: string;
  /**
   * Unique code customers enter (e.g., WELCOME10).
   */
  code: string;
  /**
   * A short note for what this coupon is for.
   */
  description: string;
  /**
   * Turn this coupon on or off for all customers.
   */
  isActive?: boolean | null;
  discountType: 'percentage' | 'fixed' | 'freeShipping';
  /**
   * Enter value (e.g., 15 for 15%, or 500 for Rs. 500).
   */
  discountValue?: number | null;
  /**
   * Optional: Cap the percentage discount at this amount.
   */
  maximumDiscount?: number | null;
  /**
   * Optional: Coupon applies if cart total is above this amount.
   */
  minimumPurchaseAmount?: number | null;
  /**
   * Coupon becomes active from this date and time.
   */
  startDate?: string | null;
  /**
   * Coupon will not be valid after this date and time.
   */
  expiryDate?: string | null;
  /**
   * Total number of times this coupon can be used across all customers.
   */
  totalUsageLimit?: number | null;
  /**
   * How many times a single customer can use this coupon.
   */
  usageLimitPerUser?: number | null;
  /**
   * If ON, this coupon can be used even if a product is already on sale.
   */
  isStackable?: boolean | null;
  applicableTo?: ('entireOrder' | 'specificProducts' | 'specificCategories') | null;
  /**
   * The coupon will ONLY apply to these selected products.
   */
  applicableProducts?: (string | Product)[] | null;
  /**
   * The coupon will ONLY apply to products within these selected categories.
   */
  applicableCategories?: (string | Category)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * A short tagline displayed below the main title.
   */
  subtitle?: string | null;
  slug: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    /**
     * Browser tab aur search results mein nazar aane wala title (50-60 chars).
     */
    metaTitle?: string | null;
    /**
     * Search results ke liye summary (150-160 chars).
     */
    metaDescription?: string | null;
    /**
     * Jab ye page Facebook ya WhatsApp par share hoga, to ye image dikhegi.
     */
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "couponBanners".
 */
export interface CouponBanner {
  id: string;
  /**
   * Sirf admin panel mein pehchanne ke liye (e.g., "Ramadan Offer Banner").
   */
  title: string;
  /**
   * Is banner par click karke user kahan jayega?
   */
  link?:
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null);
  mediaType?: ('image' | 'video') | null;
  mediaUrls?: {
    mobile?: (string | null) | Media;
    tablet?: (string | null) | Media;
    desktop?: (string | null) | Media;
  };
  width?: {
    mobile?: string | null;
    tablet?: string | null;
    desktop?: string | null;
  };
  height?: {
    mobile?: string | null;
    tablet?: string | null;
    desktop?: string | null;
  };
  objectFit?: ('cover' | 'contain') | null;
  altText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heroCarousel".
 */
export interface HeroCarousel {
  id: string;
  /**
   * Yeh title banner ke upar bari heading mein nazar aayega (Optional agar image me text ho).
   */
  title: string;
  /**
   * Yeh title ke neeche choti line mein nazar aayega.
   */
  subtitle?: string | null;
  buttonText?: string | null;
  /**
   * Internal links ke liye "/slug" aur external ke liye poora URL daalein.
   */
  link: string;
  /**
   * Recommended Size: 1920x600 pixels.
   */
  desktopImage: string | Media;
  /**
   * Recommended Size: 750x900 pixels.
   */
  mobileImage: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'brands';
        value: string | Brand;
      } | null)
    | ({
        relationTo: 'campaigns';
        value: string | Campaign;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'coupons';
        value: string | Coupon;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'couponBanners';
        value: string | CouponBanner;
      } | null)
    | ({
        relationTo: 'heroCarousel';
        value: string | HeroCarousel;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  image?: T;
  description?: T;
  desktopBanner?: T;
  mobileBanner?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  assetCategory?: T;
  customFolderName?: T;
  cloudinaryId?: T;
  cloudinaryUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  videoUrl?: T;
  variants?:
    | T
    | {
        name?: T;
        sku?: T;
        price?: T;
        salePrice?: T;
        stock?: T;
        inStock?: T;
        images?: T;
        attributes?:
          | T
          | {
              name?: T;
              value?: T;
              id?: T;
            };
        weight?: T;
        dimensions?:
          | T
          | {
              height?: T;
              width?: T;
              depth?: T;
            };
        id?: T;
      };
  description?: T;
  categories?: T;
  brand?: T;
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  shippingAndReturns?: T;
  rating?: T;
  activeCampaigns?: T;
  isBestSeller?: T;
  isNewArrival?: T;
  isFeatured?: T;
  isOnDeal?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns_select".
 */
export interface CampaignsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  isActive?: T;
  startDate?: T;
  endDate?: T;
  banner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  user?: T;
  product?: T;
  rating?: T;
  comment?: T;
  reviewImage?: T;
  isApproved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  description?: T;
  isActive?: T;
  discountType?: T;
  discountValue?: T;
  maximumDiscount?: T;
  minimumPurchaseAmount?: T;
  startDate?: T;
  expiryDate?: T;
  totalUsageLimit?: T;
  usageLimitPerUser?: T;
  isStackable?: T;
  applicableTo?: T;
  applicableProducts?: T;
  applicableCategories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  slug?: T;
  body?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "couponBanners_select".
 */
export interface CouponBannersSelect<T extends boolean = true> {
  title?: T;
  link?: T;
  mediaType?: T;
  mediaUrls?:
    | T
    | {
        mobile?: T;
        tablet?: T;
        desktop?: T;
      };
  width?:
    | T
    | {
        mobile?: T;
        tablet?: T;
        desktop?: T;
      };
  height?:
    | T
    | {
        mobile?: T;
        tablet?: T;
        desktop?: T;
      };
  objectFit?: T;
  altText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heroCarousel_select".
 */
export interface HeroCarouselSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  buttonText?: T;
  link?: T;
  desktopImage?: T;
  mobileImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  siteName: string;
  siteLogo?: (string | null) | Media;
  storeContactEmail?: string | null;
  storePhoneNumber?: string | null;
  storeAddress?: string | null;
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    twitter?: string | null;
  };
  topBarAnnouncements?:
    | {
        message?: string | null;
        id?: string | null;
      }[]
    | null;
  secondaryNavLinks?:
    | {
        label: string;
        url: string;
        position?: ('left' | 'right') | null;
        isHighlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  shippingRules?:
    | {
        name: string;
        minAmount: number;
        cost: number;
        isOnCall?: boolean | null;
        id?: string | null;
      }[]
    | null;
  inventorySettings?: {
    lowStockThreshold?: number | null;
    alertRecipientEmail?: string | null;
  };
  searchSettings?: {
    trendingKeywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
    popularCategories?: (string | Category)[] | null;
  };
  /**
   * Percentages deducted from Gross Sale Price (e.g., Bank Charges 3%, Platform Fee 2%).
   */
  globalFixedFees?:
    | {
        label: string;
        percentage: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Based on your Excel plan: Define Profit and Ad Spend based on the Buying Price (Cost).
   */
  pricingLogicTiers?:
    | {
        minCost: number;
        maxCost: number;
        profitPercent: number;
        adSpendPercent: number;
        visualDiscount?: number | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Browser tab aur search results mein nazar aane wala title (50-60 chars).
     */
    metaTitle?: string | null;
    /**
     * Search results ke liye summary (150-160 chars).
     */
    metaDescription?: string | null;
    /**
     * Jab ye page Facebook ya WhatsApp par share hoga, to ye image dikhegi.
     */
    ogImage?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: string;
  title: string;
  /**
   * A short tagline displayed below the main title.
   */
  subtitle?: string | null;
  faqList?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Browser tab aur search results mein nazar aane wala title (50-60 chars).
     */
    metaTitle?: string | null;
    /**
     * Search results ke liye summary (150-160 chars).
     */
    metaDescription?: string | null;
    /**
     * Jab ye page Facebook ya WhatsApp par share hoga, to ye image dikhegi.
     */
    ogImage?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  title?: string | null;
  /**
   * Build your homepage by adding and dragging these blocks.
   */
  pageSections?:
    | (
        | {
            desktopLayout?: ('grid' | 'mosaic-left' | 'mosaic-right' | 'hero-stack') | null;
            gridColumns?: number | null;
            heightMode?: ('auto' | 'aspect' | 'fixed' | 'custom') | null;
            aspectRatio?: ('aspect-video' | 'aspect-[4/3]' | 'aspect-square' | 'aspect-[21/9]') | null;
            fixedHeight?: ('h-[300px]' | 'h-[500px]' | 'h-[700px]') | null;
            customHeightPx?: number | null;
            mobileBehavior?: ('stack' | 'scroll' | 'grid-2') | null;
            containerSettings?: {
              fullWidth?: boolean | null;
              gap?: ('0' | '2' | '4' | '8') | null;
              roundedCorners?: ('none' | 'sm' | 'xl' | '2xl' | 'full') | null;
            };
            banners?:
              | {
                  desktopImage: string | Media;
                  mobileImage?: (string | null) | Media;
                  altText: string;
                  link?: string | null;
                  heading?: string | null;
                  subheading?: string | null;
                  buttonText?: string | null;
                  contentPosition?: ('center' | 'bottom-left' | 'bottom-center' | 'top-left') | null;
                  overlayOpacity?: number | null;
                  textColor?: ('text-white' | 'text-black') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bannerSection';
          }
        | {
            title: string;
            subtitle?: string | null;
            fetchStrategy: 'campaign' | 'category' | 'manual' | 'tag';
            selectedCampaign?: (string | null) | Campaign;
            selectedCategory?: (string | null) | Category;
            manualProducts?: (string | Product)[] | null;
            tagType?: ('newArrivals' | 'bestSellers' | 'featured') | null;
            viewType?: ('slider' | 'grid') | null;
            backgroundStyle?: ('white' | 'gradient' | 'gray') | null;
            enableTimer?: boolean | null;
            endTime?: string | null;
            showSideBanner?: boolean | null;
            sideBanner?: {
              image: string | Media;
              link?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'dealSection';
          }
        | {
            /**
             * e.g. New Arrivals, Best Sellers
             */
            title: string;
            type?: ('newest' | 'best-selling' | 'featured' | 'manual') | null;
            /**
             * Select products manually (Drag to reorder).
             */
            manualProducts?: (string | Product)[] | null;
            /**
             * Enable this to show a banner on the left side of the product slider.
             */
            showSideBanner?: boolean | null;
            sideBanner?: {
              image: string | Media;
              link?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'productShowcase';
          }
        | {
            title: string;
            /**
             * Choose at least 3 categories to display in the carousel.
             */
            categories: (string | Category)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'categoryShowcase';
          }
        | {
            title: string;
            items?:
              | {
                  category: string | Category;
                  /**
                   * e.g., "50-80% OFF" or "Under Rs. 999"
                   */
                  discountText: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'categoryGrid';
          }
        | {
            /**
             * Select a pre-made coupon design from the Coupon Banners list.
             */
            couponReference?: (string | null) | CouponBanner;
            fullWidth?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'couponSection';
          }
        | {
            title?: string | null;
            /**
             * If left empty, top 8 brands will be shown automatically (managed in frontend).
             */
            manualBrands?: (string | Brand)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'brandSection';
          }
        | {
            type?: ('trust' | 'newsletter' | 'infiniteGrid') | null;
            gridTitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'layoutSection';
          }
      )[]
    | null;
  featuredProductsTitle?: string | null;
  featuredProducts?: (string | Product)[] | null;
  featuredCategoriesTitle?: string | null;
  featuredCategories?: (string | Category)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteLogo?: T;
  storeContactEmail?: T;
  storePhoneNumber?: T;
  storeAddress?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        twitter?: T;
      };
  topBarAnnouncements?:
    | T
    | {
        message?: T;
        id?: T;
      };
  secondaryNavLinks?:
    | T
    | {
        label?: T;
        url?: T;
        position?: T;
        isHighlight?: T;
        id?: T;
      };
  shippingRules?:
    | T
    | {
        name?: T;
        minAmount?: T;
        cost?: T;
        isOnCall?: T;
        id?: T;
      };
  inventorySettings?:
    | T
    | {
        lowStockThreshold?: T;
        alertRecipientEmail?: T;
      };
  searchSettings?:
    | T
    | {
        trendingKeywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        popularCategories?: T;
      };
  globalFixedFees?:
    | T
    | {
        label?: T;
        percentage?: T;
        id?: T;
      };
  pricingLogicTiers?:
    | T
    | {
        minCost?: T;
        maxCost?: T;
        profitPercent?: T;
        adSpendPercent?: T;
        visualDiscount?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  faqList?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  title?: T;
  pageSections?:
    | T
    | {
        bannerSection?:
          | T
          | {
              desktopLayout?: T;
              gridColumns?: T;
              heightMode?: T;
              aspectRatio?: T;
              fixedHeight?: T;
              customHeightPx?: T;
              mobileBehavior?: T;
              containerSettings?:
                | T
                | {
                    fullWidth?: T;
                    gap?: T;
                    roundedCorners?: T;
                  };
              banners?:
                | T
                | {
                    desktopImage?: T;
                    mobileImage?: T;
                    altText?: T;
                    link?: T;
                    heading?: T;
                    subheading?: T;
                    buttonText?: T;
                    contentPosition?: T;
                    overlayOpacity?: T;
                    textColor?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        dealSection?:
          | T
          | {
              title?: T;
              subtitle?: T;
              fetchStrategy?: T;
              selectedCampaign?: T;
              selectedCategory?: T;
              manualProducts?: T;
              tagType?: T;
              viewType?: T;
              backgroundStyle?: T;
              enableTimer?: T;
              endTime?: T;
              showSideBanner?: T;
              sideBanner?:
                | T
                | {
                    image?: T;
                    link?: T;
                  };
              id?: T;
              blockName?: T;
            };
        productShowcase?:
          | T
          | {
              title?: T;
              type?: T;
              manualProducts?: T;
              showSideBanner?: T;
              sideBanner?:
                | T
                | {
                    image?: T;
                    link?: T;
                  };
              id?: T;
              blockName?: T;
            };
        categoryShowcase?:
          | T
          | {
              title?: T;
              categories?: T;
              id?: T;
              blockName?: T;
            };
        categoryGrid?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    category?: T;
                    discountText?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        couponSection?:
          | T
          | {
              couponReference?: T;
              fullWidth?: T;
              id?: T;
              blockName?: T;
            };
        brandSection?:
          | T
          | {
              title?: T;
              manualBrands?: T;
              id?: T;
              blockName?: T;
            };
        layoutSection?:
          | T
          | {
              type?: T;
              gridTitle?: T;
              id?: T;
              blockName?: T;
            };
      };
  featuredProductsTitle?: T;
  featuredProducts?: T;
  featuredCategoriesTitle?: T;
  featuredCategories?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}